theme = "tokyonight"

[editor]
mouse = false
auto-completion = true
auto-format = false
bufferline = "always"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
soft-wrap.enable = true
soft-wrap.max-indent-retain = 80
color-modes = true
path-completion = true
shell = ["pwsh", "-c"]

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "warning"
max-diagnostics = 3

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 1000

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "file-modification-indicator", "read-only-indicator"]
center = ["file-name"]
right = ["register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
up = "no_op"
left = "no_op"
right = "no_op"
down = "no_op"
home = "no_op"
end = "no_op"

"space" = { p = "paste_clipboard_before", P = "no_op" }

A-x = "@x<A-d>"

g = { q = ":bc" }
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.normal."-"]
g = [":write-all", ":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"] # lazygit
r = ":sh cargo run"

[keys.normal.C-y]
# Open the file(s) in the current window
y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
# Open the file(s) in a vertical pane
v = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh vsplit"
# Open the file(s) in a horizontal pane
h = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh hsplit"

[keys.insert]
k = { k = "normal_mode" } # Maps `jj` to exit insert mode
up = "no_op"
left = "no_op"
right = "no_op"
down = "no_op"
home = "no_op"
end = "no_op"
esc = "no_op"

